# Generated by Django 4.1.7 on 2023-02-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobart_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='text',
            new_name='after_text',
        ),
        migrations.AddField(
            model_name='database',
            name='before_text',
            field=models.CharField(default=2020202020, max_length=300),
            preserve_default=False,
        ),
    ]
